version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: sales
    container_name: sales-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - sales

  db:
    image: mysql:5.7
    container_name: sales-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: salesapp
      MYSQL_ROOT_PASSWORD: jjdmsl
      MYSQL_PASSWORD: jjdmsl
      MYSQL_USER: salesuser
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - sales

  nginx:
    image: nginx:alpine
    container_name: sales-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - sales

networks:
  sales:
    driver: bridge